<?php
if (!is_file(GLOBAL_CONFIG_FILE)) {
    die("Wrong configuration!");
}
global $globalConfig;
require(GLOBAL_CONFIG_FILE);
global $connection;
require(CONNECTION_FILE);
//Warning: You must not edit this config file manually.
date_default_timezone_set($globalConfig['staticParameters']['default_timezone']);
global $config;
$config = (object)[
    'db'                    => (object)$connection['database'],
    'dynamic'               => (object)[],
    'timers'                => (object)[
        'ArtifactsReleaseTime'       => '',
        'wwPlansReleaseTime'         => '',
        'WWConstructStartTime'       => '',
        'WWUpLvlInterval'            => '',
        'AutoFinishTime'             => '',
        'auto_reinstall'             => $connection['auto_reinstall'],
        'auto_reinstall_start_after' => $connection['auto_reinstall_start_after'],
    ],
    'display'               => (object)[
        'disableSeasons'                                       => false,
        'showBonusRulesInBonusTab'                             => true,
        'allowAutoReloadSettingChange'                         => true,
        'fastBuilder'                                          => true,
        'showFlagsInStatistics'                                => false,
        'smallResourcesFontSize'                               => true,
        'showPinnedLinkList'                                   => true,
        'requireCaptchaLogin'                                  => false,
        'profileHelperButtons'                                 => true,
        'farmListHelperIconActions'                            => false,
        'includeHiddenMedals'                                  => false,
        'displayFarmlistEditAll'                               => true,
        'topHammers'                                           => true,
        'suppressIranFlag'                                     => false,
        'smallTroopsNumFontSize'                               => true,
        'clickToAdventure'                                     => false,
        'showBonusTabInStatistics'                             => true,
        'dontShowLinkListBeforeTutorial'                       => true,
        'seperateLargeAndSmallTrainingBuildingsSummaryInDorf3' => false,
        'allowWWUnusualRename'                                 => true,
        'showPlusSupportTab'                                   => false,
        'maximumMultiMessageSendNum'                           => 2,
        'allowMultiVillageOnDifferentSessions'                 => true,
        'showFarmsInStatistics'                                => false,
        'hideDailyQuestWhenOnTutorial'                         => true,
        'separateNumbers3By3'                                  => true,
        'useYooreshMedals'                                     => false,
        'auctionPricePerItemFloatingPoints'                    => 2,
        'showOnlinePlayers'                                    => true,
        'showCopyright'                                        => true,
        'showCountryFlagsInGeneralStatistics'                  => true,
    ],
    'allianceBonus'         => (object)[
        'donate_reset_interval' => 86400,
        'week_reset_interval'   => 7 * 86400,
    ],
    'quest'                 => (object)[
        'multiplyRewards' => true,
    ],
    'auction'               => (object)[
        'auctionTime'                => 86400,
        'buyInactiveAuctionBySystem' => true,
        'fakeAuction'                => (object)[
            'enabled'                         => TRUE,
            'interval'                        => 1800,
            'SpreadOutRandomlyBetweenPlayers' => false,
            'SpreadOutTimeout'                => 6 * 3600,
        ],
    ],
    'settings'              => (object)[
        'advanced'           => (object)[
            'maxAverageClicksPerSecond' => 25,
            'mimMessagePop'             => 100,
            'voucherEnabled'            => TRUE,
            'registerAutoClose'         => false,
            'refLimit'                  => 10,
        ],
        'engine_filename'    => $connection['engine_filename'],
        'session_timeout'    => $globalConfig['staticParameters']['session_timeout'],
        'online_timeout'     => 600,
        'worldId'            => $connection['worldId'],
        'serverName'         => $connection['serverName'],
        'worldUniqueId'      => 0,
        'indexUrl'           => $globalConfig['staticParameters']['indexUrl'],
        'global_css_class'   => $globalConfig['staticParameters']['global_css_class'],
        'gameWorldUrl'       => $connection['gameWorldUrl'],
        'default_language'   => $globalConfig['staticParameters']['default_language'],
        'selectedLang'       => $globalConfig['staticParameters']['default_language'],
        'availableLanguages' => (object)[
            'ir' => (object)[
                'title'      => 'Travian ' . $connection['worldId'],
                'direction'  => 'RTL',
                'ForumUrl'   => $globalConfig['staticParameters']['forumUrl'],
                'AnswersUrl' => $globalConfig['staticParameters']['answersUrl'],
                'name'       => 'فارسي',
                'locale'     => 'fa-IR',
                'country'    => 'ir',
            ],
            'ae' => (object)[
                'title'      => 'Travian ' . $connection['worldId'] . '',
                'direction'  => 'RTL',
                'ForumUrl'   => $globalConfig['staticParameters']['forumUrl'],
                'AnswersUrl' => $globalConfig['staticParameters']['answersUrl'],
                'name'       => 'Arabic',
                'locale'     => 'ar-AE',
                'country'    => 'ae',
            ],
            'en' => (object)[
                'title'      => 'Travian ' . $connection['worldId'] . '',
                'direction'  => 'LTR',
                'ForumUrl'   => $globalConfig['staticParameters']['forumUrl'],
                'AnswersUrl' => $globalConfig['staticParameters']['answersUrl'],
                'name'       => 'English',
                'locale'     => 'en-US',
                'country'    => 'en',
            ],
            'gr' => (object)[
                'title'      => 'Travian ' . $connection['worldId'] . '',
                'direction'  => 'LTR',
                'ForumUrl'   => $globalConfig['staticParameters']['forumUrl'],
                'AnswersUrl' => $globalConfig['staticParameters']['answersUrl'],
                'name'       => 'Ελληνικά',
                'locale'     => 'el-GR',
                'country'    => 'gr',
            ],
            /*'tr' => (object)[
                'title'      => 'Travian ' . $connection['worldId'] . '',
                'direction'  => 'LTR',
                'ForumUrl'   => $globalConfig['staticParameters']['forumUrl'],
                'AnswersUrl' => $globalConfig['staticParameters']['answersUrl'],
                'name'       => 'Turkish',
                'locale'     => 'tr-TR',
                'country'    => 'tr',
            ],*/
        ],
        'smallMapEnabled'    => true,
        'secure_hash_code'   => $connection['secure_hash_code'],
    ],
    'game'                  => (object)[
        'speed'                                => $connection['speed'],
        'movement_speed_increase'              => 1,
        'extra_training_time_multiplier'       => 1,
        'start_time'                           => 0,
        'round_length'                         => $connection['round_length'],
        'round_length_real'                    => $connection['round_length'],
                'round_length_orig'                    => $connection['round_length'],

	'storage_multiplier'                   => 1,
        'cranny_multiplier'                    => 1,
        'trap_multiplier'                      => 1,
        'cage_multiplier'                      => 1,
        'protection_time'                      => 3 * 3600,
        'vacationDays'                         => 21,
        'farmListInterval'                     => 30,
        'autoRaidInterval'                     => 60,
        'useMilSeconds'                        => FALSE,
        'useNanoseconds'                       => FALSE,
        'auction_package_multiplier'           => 1,
        'medals_interval'                      => 6 * 3600,
        'dailyQuestInterval'                   => 24 * 60 * 60,
        'evasion_time'                         => 90,
        'starvation'                           => true,
        'checkLastReturnForEvasion'            => false,
        'catapultAvailableTime'                => 0,
        'maxTrapperCount'                      => -1,
        'changeCapitalOnZeroPop'               => true,
        'attackNewVillageInGreyArea'           => true,
        'firstVillageCreationFieldsLevel'      => 0,
        'otherVillageCreationFieldsLevel'      => 0,
        'allowPlusInWW'                        => true,
        'usePeriodicTradeRoutes'               => false,
        'allowDemolishNowInWW'                 => false,
        'allowUpgradeToMaxLevelInWW'           => true,
        'disallowAllianceInviteAfterWWRelease' => false,
        'disallowAllianceKickAfterWWRelease'   => false,
        "ignoreMoralPointsInAttacks"           => false, //really important!
        'allowNewTribes'                       => true,
        'deletionTime'                         => 3 * 83400,
    ],
    'gold'                  => (object)[
        'accountChangeNameGold'          => 20,
        'allianceBonus3xGold'            => 3,
        'goldClubGold'                   => 100,
        'startGold'                      => 0,
        'dailyGold'                      => 0,
        'plusGold'                       => 25,
        'plusAccountDurationSeconds'     => 7200,
        'productionBoostGold'            => 10,
        'productionBoostDurationSeconds' => 3600,
        'finishNowGold'                  => 2,
        'masterBuilderGold'              => 1,
        'exchangeResourcesGold'          => 3, //default 3
        'completeDemolishGold'           => 5,//default: 5
        'vacationAbortGold'              => 10, //default: 10
        'invitePlayerGold'               => 20, //default: 10
        'autoRaidSilver'                 => 20,
        'voucherTaxPercent'              => 10,
        'voucherExpireDays'              => 90,
        'changeName'                     => (object)[
            'freeTimes'                 => 3,
            'freeTillPopulation'        => 50,
            'impossibleAfterPopulation' => 500,
        ],
    ],
    'masterBuilder'         => (object)[
        'maxTasksInWonder'     => 2,
        'maxTasksInNoneWonder' => 3,
    ],
    'farms'                 => (object)[
        'bigFarmsCount'            => 0,
        'bigFarmsResourcesLevel'   => 12,
        'bigFarmsStorageCount'     => 1,
        'smallFarmsCount'          => 0,
        'smallFarmsResourcesLevel' => 8,
        'smallFarmsStorageCount'   => 1,
    ],
    'custom'                => (object)[
        'allowInterruptionInGame' => IS_DEV,
        'batchCelebration'                        => true,
        'allowResourcesToGoToMaximumPossible'     => true,
        'saveRemainingGold'                       => true,
        'disallowAutoRaidMoreThanOnePerAccount'   => false,
        'paymentWizardBuyGoldEnabled'             => true,
        'refillFarmsOnTop10Reset'                 => true,
        'useCaptchaForFarmlistProtection'         => false,
        'wwCount'                                 => 13,
        'removeReportsBelow30Percent'             => true,
        'allowOneFarmListPerAccount'              => false,
        'allowOneFarmListPerVillage'              => false,
        'startAdventures'                         => 3,
        'skipProtectionOnAttack'                  => true,
        'needAllianceWWPlan'                      => true,
        'allowEvasionForAllVillages'              => false,
        'removeProtectionAfterReleaseOfWWPlans'   => false,
        'allowOnlyOneWWVillagePerAccount'         => false,
        'wwPlansEnabled'                          => TRUE,
        'activateWWPlanOnCapture'                 => false,
        'serverIsFreeGold'                        => FALSE,
        'usePopulationAsClimbersRank'             => false,
        'attackWWOnLevelUp'                       => true,
        'allowUpgradeResourcesToMaxLevel'         => true,
        'destroyVillageOnZeroPop'                 => true,
        'disableEscapeOnVillageZeroPop'           => false,
        'cataSpeedLowerRate'                      => 15,
        'cataSpeedLowerRateAfterWWPlanRelease'    => 1,
        'cataSpeedLowerRateAfterArtifactsRelease' => 5,
        'reduceCataSpeedInAttacks'                => false,
        'reduceCataSpeedInNatarAttacks'           => false,
        'protectFarmsTill'                        => 0,
        'delayAuctions'                           => false,
        'autoRaidEnabled'                         => false,
        'startMedalsAtStartOfWeek'                => false,
        'realCancelAttack'                        => true,
        'makeAuctionsCheaperInSell'               => false,
        'decreaseItemsPriceInAuction'             => true,
        'allowVouchersOnlyOnSameEmail'            => true,
        'allianceMembersLimit'                    => 60,
        'useSessionCheckerInsteadOfDB'            => true,
        'removeReports'                           => 21600,
        'activationReminderInterval'              => 0,
        'activationProgressReminderInterval'      => 0,
        'removeVillageFromFarmListOnCapture' 	  => true,
    ],
    'bonus'                 => (object)[
        'bonusGoldWinner'            => 250,
        'bonusGoldSecondWinner'      => 0,
        'bonusGoldThirdWinner'       => 0,
        'bonusGoldTopAlliance'       => 50,
        'bonusGoldTopAllianceCount'  => 3,
        'bonusGoldTopAllianceMinPop' => 500,
        'bonusGoldTopOff'            => 100,
        'bonusGoldTopDef'            => 100,
        'bonusGoldTopClimber'        => 100,
        'bonusGoldTopOffHammer'      => 100,
        'bonusGoldTopDefHammer'      => 100,
        'top10'                      => (object)[
            'topRaider'   => (object)[
                'enabled' => false,
                'ranks'   => [
                    1 => 100,
                    2 => 50,
                    3 => 25
                ]
            ],
            'topClimber'  => (object)[
                'enabled' => false,
                'ranks'   => [
                    1 => 100,
                    2 => 50,
                    3 => 25
                ]
            ],
            'topDefender' => (object)[
                'enabled' => false,
                'ranks'   => [
                    1 => 100,
                    2 => 50,
                    3 => 25
                ]
            ],
            'topAttacker' => (object)[
                'enabled' => false,
                'ranks'   => [
                    1 => 100,
                    2 => 50,
                    3 => 25
                ]
            ]
        ],
    ],
    'heroConfig'            => (object)[
        'resourcesMultiplier'                   => 1,
        'allowHeroTrainingHelmetsInAllVillages' => false,
        "heroItemsSettings"                     => (object)[
            "heroIncreaseSpeed"                 => 1,
            "heroExtraExperienceGainRate"       => 1,
            "heroRegenerationRate"              => 1,
            "heroExtraCulturePointsRate"        => 1,
            "heroTrainingSpeedRate"             => 1,
            "heroResistantRate"                 => 1,
            "heroIncreaseHeroPower"             => 1,
            "heroIncreaseSpeedAllianceRate"     => 1,
            "heroIncreaseSpeedOwnRate"          => 1,
            "heroRaidBagRate"                   => 1,
            "natarsIncreasePowerAgainstPercent" => 1,
            "heroIncreaseUnitPower"             => 1,
            "heroMinDistanceRate"               => 1,
            "heroDistanceSpeedRate"             => 1,
            "heroIncreaseSpeedRate"             => 1,
            "heroReviveRate"                    => 1,
            "heroReviveArrivalTimeRate"         => 1,
            "heroArtWorkRate"                   => 1,
        ],
        "waterBucketsPerDay"                    => 1,
    ],
    'extraSettings'         => (object)[
        'upgradeToMaxLevel'        => (object)['enabled' => false, 'coins' => 6],
        'upgradeStorageToMaxLevel' => (object)['enabled' => false, 'coins' => 15],
        'addFarms'                 => (object)['enabled' => false, 'coins' => 70, 'enableAfter' => 3 * 3600],
        'smithyMaxLevel'           => (object)['enabled' => false, 'coins' => 10],
        'generalOptions'           => (object)[
            'buyAdventure'            => (object)['enabled' => false, 'coins' => 1],
            'upgradeAllResourcesTo20' => (object)['enabled' => false, 'coinsCapital' => 200, 'coinsNoNCapital' => 100],
            'upgradeAllResourcesTo30' => (object)['enabled' => false, 'coins' => 700],
            'rallyPointTo20'          => (object)['enabled' => FALSE, 'coins' => 15],
            'oneHourOfProduction'     => (object)['enabled' => FALSE, 'coins' => 280],
            'finishTraining'          => (object)['enabled' => false, 'threshold' => 1800],
            'fasterTraining'          => (object)['enabled' => false, 'coins' => 100, 'percent' => 25, 'duration' => 2],
            'cancelTrainingQueue'     => (object)['enabled' => FALSE, 'coins' => 50],
            'increaseStorage'         => (object)['enabled' => false, 'coins' => 25],
            'smithyUpgradeAllToMax'   => (object)['enabled' => false, 'coins' => 80],
            'academyResearchAll'      => (object)['enabled' => false, 'coins' => 50],
        ],
        // hour based
        'moreProtection'           => (object)[
            'maxPerDay'         => 6,
            'allowWithArtifact' => false,
            'packages'          => [
                ['enabled' => false, 'coins' => 75, 'duration' => 1],
                ['enabled' => false, 'coins' => 150, 'duration' => 3],
                ['enabled' => false, 'coins' => 250, 'duration' => 6],
            ],
        ],
        //duration in hours
        'power'                    => (object)[
            'atkBonus' => (object)['enabled' => false, 'coins' => 45, 'duration' => 3, 'percent' => 15],
            'defBonus' => (object)['enabled' => false, 'coins' => 45, 'duration' => 3, 'percent' => 15],
        ],
        'buyAnimal'                => [
            'buyInterval' => 0,
            'enabled'     => TRUE,
            'packages'    => [
                [
                    'coins'    => 10,
                    'modifier' => 1,
                    'delivery' => 5
                ],
                [
                    'coins'    => 20,
                    'modifier' => 2,
                    'delivery' => 5
                ],
                [
                    'coins'    => 40,					
                    'modifier' => 4,
                    'delivery' => 5
                ],
                [
                    'coins'    => 80,
                    'modifier' => 8,
                    'delivery' => 5
                ],
                [
                    'coins'    => 160,
                    'modifier' => 16,
                    'delivery' => 5
                ]
            ],
        ],
        'buyBuildings'             => [
            'buyInterval' => 0,
            'enabled'     => FALSE,
            'packages'    => [
                'buildMaxWarehouse' => (object)['name'=> 'buildMaxWarehouse','id'=> 1,'bid'=>'10', 'img'=>'g10', 'enabled' => true, 'delivery' => 0, 'coins' => 10],
                'buildMaxGranary' => (object)['name'=>'buildMaxGranary','id'=> 2,'bid'=>'11','img'=>'g11', 'enabled' => true, 'delivery' => 0, 'coins' => 10],
                'upgradeMainBuildingTo20' => (object)['name'=>'upgradeMainBuildingTo20','id'=> 3,'bid'=>'15','img'=>'g15', 'enabled' => true, 'delivery' => 0, 'coins' => 10],
                'buildMaxRallyPoint' => (object)['name'=>'buildMaxRallyPoint','id'=> 4,'bid'=>'16','img'=>'g16', 'enabled' => true, 'delivery' => 0, 'coins' => 20],
                'buildMaxBarracks' => (object)['name'=>'buildMaxBarracks','id'=> 5,'bid'=>'19','img'=>'g19', 'enabled' => true, 'delivery' => 0, 'coins' => 30],
                'buildMaxStable' => (object)['name'=>'buildMaxStable','id'=> 6,'bid'=>'20','img'=>'g20', 'enabled' => true, 'delivery' => 0, 'coins' => 30],
                'buildMaxWorkshop' => (object)['name'=>'buildMaxWorkshop','id'=> 7,'bid'=>'21','img'=>'g21', 'enabled' => true, 'delivery' => 0, 'coins' => 30],
                'buildMaxAcademy' => (object)['name'=>'buildMaxAcademy','id'=> 8,'bid'=>'22','img'=>'g22', 'enabled' => true, 'delivery' => 0, 'coins' => 20],
                'buildMaxSmithy' => (object)['name'=>'buildMaxSmithy','id'=> 9,'bid'=>'13','img'=>'g13', 'enabled' => true, 'delivery' => 0, 'coins' => 30],
                'buildMaxTrasury' => (object)['name'=>'buildMaxTrasury','id'=> 10,'bid'=>'27','img'=>'g27', 'enabled' => true, 'delivery' => 0, 'coins' => 30],
                'buildMaxTournametnSquare' => (object)['name'=>'buildMaxTournametnSquare','id'=> 11,'bid'=>'14','img'=>'g14', 'enabled' => true, 'delivery' => 0, 'coins' => 30],
                'upgradeAllResourcesTo5' => (object)['name'=>'upgradeAllResourcesTo5','id'=> 12,'bid'=>'res5','img'=>'', 'enabled' => true, 'delivery' => 0, 'coins' => 150],
                'upgradeAllResourcesTo10' => (object)['name'=>'upgradeAllResourcesTo10','id'=> 13,'bid'=>'res10','img'=>'', 'enabled' => true, 'delivery' => 0, 'coins' => 300],
                'upgradeAllResourcesTo20' => (object)['name'=>'upgradeAllResourcesTo20','id'=> 14,'bid'=>'res20','img'=>'', 'enabled' => true, 'delivery' => 0, 'coinsCapital' => 500, 'coins' => 400],
                'upgradeAllResourcesTo30' => (object)['name'=>'upgradeAllResourcesTo30','id'=> 15,'bid'=>'res30','img'=>'', 'enabled' => false, 'delivery' => 0, 'coins' => 700],
            ],
        ],
        'buyResources'             => [
            'buyInterval' => 0,
            'enabled'     => FALSE,
            'packages'    => [
                ['id'=> 1, 'resource' => 1, 'hours' => 6, 'coins' => 60, 'delivery' => 0, 'is_single' => 1, 'name' => 'Wood'],
                ['id'=> 2, 'resource' => 2, 'hours' => 6, 'coins' => 60, 'delivery' => 0, 'is_single' => 1, 'name' => 'Clay'],
                ['id'=> 3, 'resource' => 3, 'hours' => 6, 'coins' => 60, 'delivery' => 0, 'is_single' => 1, 'name' => 'Stone'],
                ['id'=> 4, 'resource' => 4, 'hours' => 6, 'coins' => 60, 'delivery' => 0, 'is_single' => 1, 'name' => 'Crop'],
                ['id'=> 5, 'resource' => -1, 'hours' => 6, 'coins' => 200, 'delivery' => 0, 'is_single' => 0, 'name' => 'Small Combo Package'],
                ['id'=> 6, 'resource' => -1, 'hours' => 12, 'coins' => 400, 'delivery' => 0, 'is_single' => 0, 'name' => 'Medium Combo Package'],
                ['id'=> 7, 'resource' => -1, 'hours' => 24, 'coins' => 800, 'delivery' => 0, 'is_single' => 0, 'name' => 'Large Combo Package'],
            ],
        ],
        'buyTroops'                => [
            'buyInterval' => 0,
            'enabled'     => FALSE,
            'packages'    => [
                1 => [
                    ['id'=> 1, 'hours' => 1, 'coins' => 10, 'delivery' => 0],
                    ['id'=> 2, 'hours' => 2, 'coins' => 20, 'delivery' => 0],
                    ['id'=> 3, 'hours' => 4, 'coins' => 40, 'delivery' => 0],
                    ['id'=> 4, 'hours' => 8, 'coins' => 80, 'delivery' => 0],
                    ['id'=> 5, 'hours' => 12, 'coins' => 120, 'delivery' => 0],
                    ['id'=> 6, 'hours' => 24, 'coins' => 240, 'delivery' => 0],
                ],
                2 => [
                    ['id'=> 1, 'hours' => 1, 'coins' => 10, 'delivery' => 0],
                    ['id'=> 2, 'hours' => 2, 'coins' => 20, 'delivery' => 0],
                    ['id'=> 3, 'hours' => 4, 'coins' => 40, 'delivery' => 0],
                    ['id'=> 4, 'hours' => 8, 'coins' => 80, 'delivery' => 0],
                    ['id'=> 5, 'hours' => 12, 'coins' => 120, 'delivery' => 0],
                    ['id'=> 6, 'hours' => 24, 'coins' => 240, 'delivery' => 0],
                ],
                3 => [
                    ['id'=> 1, 'hours' => 1, 'coins' => 10, 'delivery' => 0],
                    ['id'=> 2, 'hours' => 2, 'coins' => 20, 'delivery' => 0],
                    ['id'=> 3, 'hours' => 4, 'coins' => 40, 'delivery' => 0],
                    ['id'=> 4, 'hours' => 8, 'coins' => 80, 'delivery' => 0],
                    ['id'=> 5, 'hours' => 12, 'coins' => 120, 'delivery' => 0],
                    ['id'=> 6, 'hours' => 24, 'coins' => 240, 'delivery' => 0],
                ],
                4 => [
                    ['id'=> 1, 'hours' => 1, 'coins' => 10, 'delivery' => 0],
                    ['id'=> 2, 'hours' => 2, 'coins' => 20, 'delivery' => 0],
                    ['id'=> 3, 'hours' => 4, 'coins' => 40, 'delivery' => 0],
                    ['id'=> 4, 'hours' => 8, 'coins' => 80, 'delivery' => 0],
                    ['id'=> 5, 'hours' => 12, 'coins' => 120, 'delivery' => 0],
                    ['id'=> 6, 'hours' => 24, 'coins' => 240, 'delivery' => 0],
                ],
                5 => [
                    ['id'=> 1, 'hours' => 1, 'coins' => 10, 'delivery' => 0],
                    ['id'=> 2, 'hours' => 2, 'coins' => 20, 'delivery' => 0],
                    ['id'=> 3, 'hours' => 4, 'coins' => 40, 'delivery' => 0],
                    ['id'=> 4, 'hours' => 8, 'coins' => 80, 'delivery' => 0],
                    ['id'=> 5, 'hours' => 12, 'coins' => 120, 'delivery' => 0],
                    ['id'=> 6, 'hours' => 24, 'coins' => 240, 'delivery' => 0],
                ],
                6 => [
                    ['id'=> 1, 'hours' => 1, 'coins' => 10, 'delivery' => 0],
                    ['id'=> 2, 'hours' => 2, 'coins' => 20, 'delivery' => 0],
                    ['id'=> 3, 'hours' => 4, 'coins' => 40, 'delivery' => 0],
                    ['id'=> 4, 'hours' => 8, 'coins' => 80, 'delivery' => 0],
                    ['id'=> 5, 'hours' => 12, 'coins' => 120, 'delivery' => 0],
                    ['id'=> 6, 'hours' => 24, 'coins' => 240, 'delivery' => 0],
                ]                
            ]
        ],
    ],
    'Voting'                => (object)[
        'TopG'        => (object)[
            'link'     => '',
            'interval' => 43200,
            'gold'     => 50,
        ],
        'ArenaTop100' => (object)[
            'link'     => '',
            'interval' => 43200,
            'gold'     => 50,
        ],
        'GTop100'     => (object)[
            'link'     => '',
            'interval' => 86400,
            'gold'     => 50,
        ],
    ],
    'timezones'             => [
        'general' => [
            0  => 'UTC +1',
            1  => 'UTC +2',
            2  => 'UTC +3',
            3  => 'UTC +4',
            4  => 'UTC +5',
            5  => 'UTC +6',
            6  => 'UTC +7',
            7  => 'UTC +8',
            8  => 'UTC +9',
            9  => 'UTC +10',
            10 => 'UTC +11',
            11 => 'UTC +12',
            12 => 'UTC -11',
            13 => 'UTC -10',
            14 => 'UTC -9',
            15 => 'UTC -8',
            16 => 'UTC -7',
            17 => 'UTC -6',
            18 => 'UTC -5',
            19 => 'UTC -4',
            20 => 'UTC -3',
            21 => 'UTC -2',
            22 => 'UTC -1',
            23 => 'UTC',
        ],
        'local'   => [
            441 => 'Canada/Newfoundland',
            99  => 'Europe/Paris',
            495 => 'Europe/Berlin',
            496 => 'Europe/London',
            497 => 'Asia/Amman',
            570 => 'Asia/Tehran',
            328 => 'Asia/Calcutta',
            330 => 'Asia/Dubai',
            562 => 'Australia/ACT',
        ],
    ],
    'countryCodes'          => [
        'AF' => 'Afghanistan',
        'AX' => 'Åland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Zaire',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Côte D\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island and Mcdonald Islands',
        'VA' => 'Vatican City State',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'KENYA',
        'KI' => 'Kiribati',
        'KP' => 'Korea, Democratic People\'s Republic of',
        'KR' => 'Korea, Republic of',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libyan Arab Jamahiriya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia, the Former Yugoslav Republic of',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia, Federated States of',
        'MD' => 'Moldova, Republic of',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territory, Occupied',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Réunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'PM' => 'Saint Pierre and Miquelon',
        'VC' => 'Saint Vincent and the Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome and Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia and the South Sandwich Islands',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard and Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan, Province of China',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania, United Republic of',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UM' => 'United States Minor Outlying Islands',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela',
        'VN' => 'Viet Nam',
        'VG' => 'Virgin Islands, British',
        'VI' => 'Virgin Islands, U.S.',
        'WF' => 'Wallis and Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ],
    'fakeUsersCountryCodes' => [],
    'fakeUsersCount'        => 0,
];
return $config;
